export const blog_data = [
  {
    id: 1,
    title: "Virat Kohli – The Run Machine",
    description:
      "Virat Kohli is one of the greatest modern-day batsmen, known for his consistency, aggression, and leadership. lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. ",
    image: "/images/virat-kohli.jfif",
    date: "2025-01-01",
    country: "India",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 2,
    title: "Babar Azam – Pakistan’s Pride",
    description:
      "Babar Azam is Pakistan’s premier batsman, admired for his elegant stroke play and calm leadership.",
    image: "/images/babar-azam.jfif",
    date: "2025-01-02",
    country: "Pakistan",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 3,
    title: "Joe Root – England’s Backbone",
    description:
      "Joe Root is England’s most reliable batsman, famous for his technique and match-winning innings.",
    image: "/images/joe_root.jfif",
    date: "2025-01-03",
    country: "England",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 4,
    title: "Kane Williamson – The Calm Leader",
    description:
      "Kane Williamson is known for his composure, sportsmanship, and consistent batting for New Zealand.",
    image: "/images/kane_williamson.jfif",
    date: "2025-01-04",
    country: "New Zealand",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 5,
    title: "Steve Smith – The Unorthodox Genius",
    description:
      "Steve Smith is Australia’s most successful modern batsman with a unique batting style.",
    image: "/images/steve_smith.jfif",
    date: "2025-01-05",
    country: "Australia",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 6,
    title: "Rohit Sharma – The Hitman",
    description:
      "Rohit Sharma is famous for his elegant batting and record-breaking double centuries.",
    image: "/images/rohit_sharma.jfif",
    date: "2025-01-06",
    country: "India",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 7,
    title: "Ben Stokes – England’s Match Winner",
    description:
      "Ben Stokes is an all-rounder known for his heroic performances in crucial matches.",
    image: "/images/ben_stokes.jfif",
    date: "2025-01-07",
    country: "England",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 8,
    title: "Shaheen Afridi – Pakistan’s Speedster",
    description: "Shaheen Afridi is a deadly fast bowler with swing and pace.",
    image: "/images/shaheen.jfif",
    date: "2025-01-08",
    country: "Pakistan",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 9,
    title: "Jasprit Bumrah – The Yorker King",
    description:
      "Bumrah is India’s strike bowler, known for his deadly yorkers.",
    image: "/images/bumrah.jfif",
    date: "2025-01-09",
    country: "India",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },
  {
    id: 10,
    title: "AB de Villiers – Mr. 360",
    description:
      "AB de Villiers was known for his innovative shots and explosive batting.",
    image: "/images/ab_de_villiers.jfif",
    date: "2025-01-10",
    country: "South Africa",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },
  {
    id: 11,
    title: "MS Dhoni – Captain Cool",
    description:
      "Dhoni is one of the greatest captains and finishers in cricket history.",
    image: "/images/ms_dhoni.jfif",
    date: "2025-01-11",
    country: "India",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 12,
    title: "David Warner – Australia’s Aggressor",
    description: "Warner is known for his explosive opening batting.",
    image: "/images/david_warner.jfif",
    date: "2025-01-12",
    country: "Australia",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 13,
    title: "Shakib Al Hasan – Bangladesh’s Hero",
    description: "Shakib is one of the best all-rounders in the world.",
    image: "/images/shakib.jfif",
    date: "2025-01-13",
    country: "Bangladesh",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 14,
    title: "Muttiah Muralitharan – Spin Wizard",
    description: "Murali is the highest wicket-taker in international cricket.",
    image: "/images/murali.jfif",
    date: "2025-01-14",
    country: "Sri Lanka",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 15,
    title: "Kumar Sangakkara – Elegant Batsman",
    description: "Sangakkara was known for his classy stroke play.",
    image: "/images/sangakkara.jfif",
    date: "2025-01-15",
    country: "Sri Lanka",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },

  // ---- SHORTER ENTRIES TO REACH 50 ----

  {
    id: 16,
    title: "Chris Gayle – Universe Boss",
    description: "Gayle is known for massive sixes.",
    image: "/images/gayle.jfif",
    date: "2025-01-16",
    country: "West Indies",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 17,
    title: "Trent Boult – Swing Master",
    description: "Boult is deadly with the new ball.",
    image: "/images/boult.jpg",
    date: "2025-01-17",
    country: "New Zealand",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 18,
    title: "Hardik Pandya – Power All-rounder",
    description: "Hardik brings power and pace.",
    image: "/images/hardik.jpg",
    date: "2025-01-18",
    country: "India",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 19,
    title: "Mohammad Rizwan – Reliable Opener",
    description: "Rizwan is Pakistan’s key batsman.",
    image: "/images/rizwan.jpg",
    date: "2025-01-19",
    country: "Pakistan",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 20,
    title: "Faf du Plessis – Strong Leader",
    description: "Faf is known for his consistency.",
    image: "/images/faf.jpg",
    date: "2025-01-20",
    country: "South Africa",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },

  {
    id: 21,
    title: "Wasim Akram – Sultan of Swing",
    description: "Wasim mastered swing bowling.",
    image: "/images/wasim.jpg",
    date: "2025-01-21",
    country: "Pakistan",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 22,
    title: "Inzamam-ul-Haq – Big Man",
    description: "Inzamam was a classy batsman.",
    image: "/images/inzamam.jpg",
    date: "2025-01-22",
    country: "Pakistan",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 23,
    title: "Virender Sehwag – Fearless Opener",
    description: "Sehwag attacked from ball one.",
    image: "/images/sehwag.jpg",
    date: "2025-01-23",
    country: "India",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 24,
    title: "Sourav Ganguly – Dada",
    description: "Ganguly built a strong Indian team.",
    image: "/images/ganguly.jpg",
    date: "2025-01-24",
    country: "India",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 25,
    title: "Kapil Dev – World Cup Hero",
    description: "Kapil led India to 1983 glory.",
    image: "/images/kapil.jpg",
    date: "2025-01-25",
    country: "India",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },

  {
    id: 26,
    title: "Jacques Kallis – Perfect All-rounder",
    description: "Kallis was balanced in all formats.",
    image: "/images/kallis.jpg",
    date: "2025-01-26",
    country: "South Africa",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 27,
    title: "Brian Lara – Caribbean Legend",
    description: "Lara holds record scores.",
    image: "/images/lara.jpg",
    date: "2025-01-27",
    country: "West Indies",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 28,
    title: "Imran Khan – Pakistan’s Icon",
    description: "Imran led Pakistan to WC 1992.",
    image: "/images/imran.jpg",
    date: "2025-01-28",
    country: "Pakistan",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 29,
    title: "Shahid Afridi – Boom Boom",
    description: "Afridi was famous for sixes.",
    image: "/images/afridi.jpg",
    date: "2025-01-29",
    country: "Pakistan",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 30,
    title: "Yuvraj Singh – Big Match Player",
    description: "Yuvraj shined in World Cups.",
    image: "/images/yuvraj.jpg",
    date: "2025-01-30",
    country: "India",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },

  {
    id: 31,
    title: "Rashid Khan – Afghan Star",
    description: "Rashid is a top T20 bowler.",
    image: "/images/rashid.jpg",
    date: "2025-01-31",
    country: "Afghanistan",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 32,
    title: "Moeen Ali – England’s All-rounder",
    description: "Moeen contributes in all areas.",
    image: "/images/moeen.jpg",
    date: "2025-02-01",
    country: "England",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 33,
    title: "Pat Cummins – Aussie Captain",
    description: "Cummins leads with pace.",
    image: "/images/cummins.jpg",
    date: "2025-02-02",
    country: "Australia",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 34,
    title: "Quinton de Kock – Explosive Opener",
    description: "De Kock is aggressive.",
    image: "/images/dekock.jpg",
    date: "2025-02-03",
    country: "South Africa",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 35,
    title: "Ross Taylor – Kiwi Legend",
    description: "Taylor served NZ for years.",
    image: "/images/taylor.jpg",
    date: "2025-02-04",
    country: "New Zealand",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },

  {
    id: 36,
    title: "Malinga – Yorker Specialist",
    description: "Malinga’s yorkers were deadly.",
    image: "/images/malinga.jpg",
    date: "2025-02-05",
    country: "Sri Lanka",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 37,
    title: "Tamim Iqbal – Bangla Star",
    description: "Tamim led Bangladesh.",
    image: "/images/tamim.jpg",
    date: "2025-02-06",
    country: "Bangladesh",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 38,
    title: "Andre Russell – Powerhouse",
    description: "Russell hits huge sixes.",
    image: "/images/russell.jpg",
    date: "2025-02-07",
    country: "West Indies",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 39,
    title: "Sunil Narine – Mystery Spinner",
    description: "Narine confuses batsmen.",
    image: "/images/narine.jpg",
    date: "2025-02-08",
    country: "West Indies",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 40,
    title: "Alastair Cook – England’s Wall",
    description: "Cook was a solid opener.",
    image: "/images/cook.jpg",
    date: "2025-02-09",
    country: "England",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },

  {
    id: 41,
    title: "KL Rahul – Stylish Batsman",
    description: "Rahul plays elegant shots.",
    image: "/images/rahul.jpg",
    date: "2025-02-10",
    country: "India",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 42,
    title: "Shubman Gill – Young Star",
    description: "Gill is India’s future.",
    image: "/images/gill.jpg",
    date: "2025-02-11",
    country: "India",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 43,
    title: "Naseem Shah – Young Paceman",
    description: "Naseem bowls with pace.",
    image: "/images/naseem.jpg",
    date: "2025-02-12",
    country: "Pakistan",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 44,
    title: "Haris Rauf – Express Speed",
    description: "Rauf is very fast.",
    image: "/images/rauf.jpg",
    date: "2025-02-13",
    country: "Pakistan",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 45,
    title: "Jos Buttler – England’s Finisher",
    description: "Buttler finishes games.",
    image: "/images/buttler.jpg",
    date: "2025-02-14",
    country: "England",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },

  {
    id: 46,
    title: "Mitchell Starc – Left-arm Thunder",
    description: "Starc bowls fast yorkers.",
    image: "/images/starc.jpg",
    date: "2025-02-15",
    country: "Australia",
    author: "Cricket Desk",
    author_img: "author1.jpg",
  },
  {
    id: 47,
    title: "Glenn Maxwell – Big Hitter",
    description: "Maxwell is explosive.",
    image: "/images/maxwell.jpg",
    date: "2025-02-16",
    country: "Australia",
    author: "Cricket Desk",
    author_img: "author2.jpg",
  },
  {
    id: 48,
    title: "Eoin Morgan – White-ball Leader",
    description: "Morgan changed England’s style.",
    image: "/images/morgan.jpg",
    date: "2025-02-17",
    country: "England",
    author: "Cricket Desk",
    author_img: "author3.jpg",
  },
  {
    id: 49,
    title: "Rilee Rossouw – Powerful Bat",
    description: "Rossouw hits hard.",
    image: "/images/rossouw.jpg",
    date: "2025-02-18",
    country: "South Africa",
    author: "Cricket Desk",
    author_img: "author4.jpg",
  },
  {
    id: 50,
    title: "Mohammad Nabi – Afghan Legend",
    description: "Nabi helped build Afghan cricket.",
    image: "/images/nabi.jpg",
    date: "2025-02-19",
    country: "Afghanistan",
    author: "Cricket Desk",
    author_img: "author5.jpg",
  },
];
